import React,{useEffect,useMemo,useState}from"react";
import{Bell,Clock3,CreditCard,GlassWater,LayoutDashboard,LogOut,Package,Plus,ReceiptText,ShieldAlert,Users,Wine,WalletCards}from"lucide-react";
import{createRoot}from"react-dom/client";import"./styles.css";
type Order={id:string,name:string,price:number,qty:number};
type T={id:string,name:string,guests:number,plan:"free"|"aycd"|"ala",startedAt?:number,orders:Order[]};
type A={id:string,type:string,table:string,actor:string,detail:string,amount:number,level:"red"|"orange",at:number,acknowledged:boolean};
type Bottle={id:string,customer:string,bottle:string,remain:number,date:string};
const yen=(v:number)=>new Intl.NumberFormat("ja-JP",{style:"currency",currency:"JPY",maximumFractionDigits:0}).format(v);
const total=(t:T)=>t.orders.reduce((s,o)=>s+o.price*o.qty,0);
const seed:T[]=[{id:"C1",name:"Counter 1",guests:1,plan:"aycd",startedAt:Date.now()-38*60000,orders:[{id:"a",name:"飲み放題 1h",price:1000,qty:1},{id:"b",name:"チャージ",price:500,qty:1},{id:"c",name:"テキーラ",price:500,qty:2}]},{id:"C2",name:"Counter 2",guests:0,plan:"free",orders:[]},{id:"T1",name:"Table A",guests:4,plan:"ala",orders:[{id:"d",name:"瓶ビール",price:700,qty:4},{id:"e",name:"テキーラ",price:500,qty:4}]},{id:"T2",name:"Table B",guests:2,plan:"aycd",startedAt:Date.now()-52*60000,orders:[{id:"f",name:"飲み放題 1h",price:1000,qty:2},{id:"g",name:"チャージ",price:500,qty:2}]},{id:"T3",name:"Table C",guests:0,plan:"free",orders:[]}];
const menu=[["チャージ",500,"基本"],["飲み放題 1h",1000,"基本"],["ワンドリンク",500,"ドリンク"],["瓶ビール",700,"ドリンク"],["テキーラ",500,"ショット"],["ウォッカ",500,"ショット"],["シロック",800,"ショット"],["1800",1000,"ショット"],["ピッチャー",2500,"ドリンク"],["吉四六",8000,"ボトル"],["カフェパリ",8000,"ボトル"],["オリシャン",13000,"ボトル"],["モエ",20000,"ボトル"],["ヴーヴ",22000,"ボトル"],["モエロゼ",23000,"ボトル"],["PJ",28000,"ボトル"],["ドンペリ",88000,"ボトル"]]as const;
function App(){const[login,setLogin]=useState(false),[pin,setPin]=useState(""),[page,setPage]=useState("home"),[tables,setTables]=useState<T[]>(()=>{const x=JSON.parse(localStorage.getItem("baros_v2_tables")||"null");return x||seed}),[sel,setSel]=useState("C1"),[audits,setAudits]=useState<A[]>(()=>JSON.parse(localStorage.getItem("baros_audits")||"[]")),[clock,setClock]=useState(()=>localStorage.getItem("baros_clock")==="1"),[bottles,setBottles]=useState<Bottle[]>(()=>JSON.parse(localStorage.getItem("baros_bottles")||"null")||[{id:"1",customer:"たけし",bottle:"吉四六",remain:50,date:"2026/10/01"},{id:"2",customer:"山田",bottle:"角瓶",remain:75,date:"2026/10/05"}]),[cash,setCash]=useState("");
useEffect(()=>localStorage.setItem("baros_v2_tables",JSON.stringify(tables)),[tables]);useEffect(()=>localStorage.setItem("baros_audits",JSON.stringify(audits)),[audits]);useEffect(()=>localStorage.setItem("baros_bottles",JSON.stringify(bottles)),[bottles]);useEffect(()=>localStorage.setItem("baros_clock",clock?"1":"0"),[clock]);
const sales=useMemo(()=>tables.reduce((s,t)=>s+total(t),0),[tables]),guests=tables.reduce((s,t)=>s+t.guests,0),unc=audits.filter(a=>!a.acknowledged).length,cur=tables.find(t=>t.id===sel)!;
const audit=(type:string,detail:string,amount:number,level:"red"|"orange"="orange")=>setAudits(x=>[{id:crypto.randomUUID(),type,table:cur?.name||"-",actor:"武田",detail,amount,level,at:Date.now(),acknowledged:false},...x]);
const add=(name:string,price:number)=>setTables(x=>x.map(t=>t.id!==sel?t:{...t,orders:t.orders.some(o=>o.name===name)?t.orders.map(o=>o.name===name?{...o,qty:o.qty+1}:o):[...t.orders,{id:crypto.randomUUID(),name,price,qty:1}]}));
const qty=(id:string,d:number)=>setTables(x=>x.map(t=>{if(t.id!==sel)return t;const old=t.orders.find(o=>o.id===id);if(!old)return t;const nq=old.qty+d;if(nq<=0){audit("注文取消",old.name+" を取消",old.price,"orange");return{...t,orders:t.orders.filter(o=>o.id!==id)}}return{...t,orders:t.orders.map(o=>o.id===id?{...o,qty:nq}:o)}}));
const service=(name:string,price:number)=>audit("サービス",name+" をサービス",price,price>=5000?"red":"orange");
const enter=(id:string)=>setTables(x=>x.map(t=>t.id===id?{...t,guests:2,plan:"aycd",startedAt:Date.now(),orders:[{id:crypto.randomUUID(),name:"飲み放題 1h",price:1000,qty:2},{id:crypto.randomUUID(),name:"チャージ",price:500,qty:2}]}:t));
const extend=(m:number)=>{setTables(x=>x.map(t=>t.id===sel?{...t,startedAt:(t.startedAt||Date.now())+m*60000,orders:[...t.orders,{id:crypto.randomUUID(),name:"飲み放題延長 "+m+"分",price:m===30?500:1000,qty:t.guests}]}:t));};
const checkout=()=>{setTables(x=>x.map(t=>t.id===sel?{...t,guests:0,plan:"free",startedAt:undefined,orders:[]}:t));setPage("tables")};
if(!login)return <div className="login"><div className="brand">BAR <span>OS</span></div><div className="subtitle">CHANCE · STAFF LOGIN</div><div className="pinDots">{[0,1,2,3].map(i=><i key={i} className={i<pin.length?"on":""}/>)}</div><div className="keypad">{[1,2,3,4,5,6,7,8,9].map(n=><button key={n} onClick={()=>pin.length<4&&setPin(pin+n)}>{n}</button>)}<button onClick={()=>setPin("")}>C</button><button onClick={()=>pin.length<4&&setPin(pin+"0")}>0</button><button className="gold" onClick={()=>pin.length===4&&setLogin(true)}>入店</button></div><p className="hint">デモ：4桁ならログインできます</p></div>;
return <div className="app"><aside><div className="sideBrand">BAR <span>OS</span><small>CHANCE</small></div><Nav i={<LayoutDashboard/>} l="ホーム" a={page==="home"} f={()=>setPage("home")}/><Nav i={<Users/>} l="席・注文" a={page==="tables"||page==="order"} f={()=>setPage("tables")}/><Nav i={<Wine/>} l="ボトル" a={page==="bottles"} f={()=>setPage("bottles")}/><Nav i={<ShieldAlert/>} l={"重要操作 "+(unc?"("+unc+")":"")} a={page==="audit"} f={()=>setPage("audit")}/><Nav i={<Package/>} l="在庫" a={page==="inventory"} f={()=>setPage("inventory")}/><Nav i={<Clock3/>} l="勤怠" a={page==="attendance"} f={()=>setPage("attendance")}/><Nav i={<WalletCards/>} l="レジ締め" a={page==="close"} f={()=>setPage("close")}/><div className="spacer"/><Nav i={<LogOut/>} l="ログアウト" f={()=>setLogin(false)}/></aside><main><header><div><b>BAR OS</b><span>運営ダッシュボード</span></div><button className="bell" onClick={()=>setPage("audit")}><Bell/>{unc>0&&<em>{unc}</em>}</button></header>
{page==="home"&&<>{unc>0&&<div className="alertBanner" onClick={()=>setPage("audit")}><ShieldAlert/><b>未確認の重要操作が {unc} 件あります</b><span>確認する →</span></div>}<section className="hero"><p>本日の営業</p><h1>{yen(sales)}</h1><span>{guests}名 来店中</span></section><div className="stats"><Card t="現在客数" v={guests+"名"} s="店内"/><Card t="平均客単価" v={guests?yen(Math.round(sales/guests)):"¥0"} s="リアルタイム"/><Card t="サービス" v={yen(audits.filter(a=>a.type==="サービス").reduce((s,a)=>s+a.amount,0))} s="記録"/><Card t="重要操作" v={unc+"件"} s="未確認"/></div><div className="quick"><button onClick={()=>setPage("tables")}><Plus/>新規来店</button><button onClick={()=>setPage("tables")}><GlassWater/>注文</button><button onClick={()=>setPage("bottles")}><Wine/>ボトルキープ</button><button onClick={()=>setPage("close")}><WalletCards/>レジ締め</button></div></>}
{page==="tables"&&<><Title h="席管理" p="空席タップで新規来店・利用中席で注文"/><div className="tableGrid">{tables.map(t=>{const r=t.plan==="aycd"&&t.startedAt?60-Math.floor((Date.now()-t.startedAt)/60000):null;return <button key={t.id} className={"tableCard "+(t.guests?"busy":"empty")+" "+(r!==null&&r<=10?"danger":"")} onClick={()=>{setSel(t.id);t.guests?setPage("order"):enter(t.id)}}><strong>{t.name}</strong><span>{t.guests?t.guests+"名":"空席"}</span>{t.guests>0&&<><b>{yen(total(t))}</b>{r!==null&&<small>飲放 残り {Math.max(r,0)}分</small>}</>}</button>})}</div></>}
{page==="order"&&<><div className="pageTitle"><div><h2>{cur.name}</h2><p>{cur.guests}名 · 現在 {yen(total(cur))}</p></div><button className="checkout" onClick={checkout}><ReceiptText/> 会計</button></div>{cur.plan==="aycd"&&<div className="extend"><b>飲み放題</b><button onClick={()=>extend(30)}>＋30分</button><button onClick={()=>extend(60)}>＋60分</button></div>}<h3>現在の注文</h3><div className="orderList">{cur.orders.map(o=><div className="orderRow" key={o.id}><span>{o.name}</span><b>{yen(o.price*o.qty)}</b><div><button onClick={()=>qty(o.id,-1)}>−</button><strong>{o.qty}</strong><button onClick={()=>qty(o.id,1)}>＋</button></div></div>)}</div><h3>商品追加</h3><div className="menuGrid">{menu.map(m=><div className="menuItem" key={m[0]}><small>{m[2]}</small><b>{m[0]}</b><span>{yen(m[1])}</span><div><button onClick={()=>add(m[0],m[1])}>追加</button><button className="service" onClick={()=>service(m[0],m[1])}>サービス</button></div></div>)}</div></>}
{page==="bottles"&&<><Title h="ボトルキープ" p="お客様名・残量・開栓日"/><div className="bottleList">{bottles.map(b=><div className="bottleCard" key={b.id}><div><b>{b.customer}</b><span>{b.bottle} · {b.date}</span></div><strong>{b.remain}%</strong><div className="bottleBtns">{[100,75,50,25,0].map(v=><button className={b.remain===v?"selected":""} onClick={()=>setBottles(x=>x.map(y=>y.id===b.id?{...y,remain:v}:y))}>{v}%</button>)}</div></div>)}</div></>}
{page==="audit"&&<><Title h="重要操作ログ" p="取消・サービス・返金など"/><div className="auditList">{audits.length===0?<div className="emptyState">重要操作はまだありません</div>:audits.map(a=><div className={"audit "+a.level} key={a.id}><div><b>{a.type} · {a.table}</b><span>{a.detail}</span><small>{a.actor} · {new Date(a.at).toLocaleString("ja-JP")}</small></div><div className="auditRight"><strong>{yen(a.amount)}</strong>{a.acknowledged?<span className="ok">確認済</span>:<button onClick={()=>setAudits(x=>x.map(y=>y.id===a.id?{...y,acknowledged:true}:y))}>確認しました</button>}</div></div>)}</div></>}
{page==="inventory"&&<><Title h="在庫・原価" p="売上と理論在庫をつなぐ画面"/><div className="inventory">{["角瓶","ニッカ","テキーラ","ウォッカ","吉四六","モエ","ヴーヴ"].map((x,i)=>{const v=[42,61,18,34,26,8,5][i];return <div key={x}><b>{x}</b><span>{v}%</span><progress max="100" value={v}/></div>})}</div></>}
{page==="attendance"&&<><Title h="勤怠" p="武田 裕"/><div className="attendanceCard"><Clock3/><h3>{clock?"出勤中":"未出勤"}</h3><p>{clock?"本日の勤務を記録しています":"出勤ボタンを押してください"}</p><button onClick={()=>setClock(!clock)}>{clock?"退勤する":"出勤する"}</button></div></>}
{page==="close"&&<><Title h="レジ締め" p="理論現金と実際の現金を照合"/><div className="attendanceCard"><WalletCards/><h3>理論売上 {yen(sales)}</h3><p>実際の現金を入力</p><input className="cashInput" inputMode="numeric" value={cash} onChange={e=>setCash(e.target.value.replace(/\D/g,""))} placeholder="例 83500"/>{cash&&<><h3>差額 {yen(Number(cash)-sales)}</h3>{Number(cash)!==sales&&<button onClick={()=>audit("レジ差額","レジ締め差額 "+yen(Number(cash)-sales),Math.abs(Number(cash)-sales),"red")}>差額を記録</button>}</>}</div></>}</main></div>}
function Nav(p:{i:React.ReactNode,l:string,a?:boolean,f:()=>void}){return <button className={"nav "+(p.a?"active":"")} onClick={p.f}>{p.i}<span>{p.l}</span></button>}function Card(p:{t:string,v:string,s:string}){return <div className="card"><span>{p.t}</span><b>{p.v}</b><small>{p.s}</small></div>}function Title(p:{h:string,p:string}){return <div className="pageTitle"><div><h2>{p.h}</h2><p>{p.p}</p></div></div>}
createRoot(document.getElementById("root")!).render(<App/>);