import React,{useEffect,useMemo,useState}from"react";
import{Bell,Clock3,CreditCard,GlassWater,LayoutDashboard,LogOut,Package,Plus,ReceiptText,ShieldAlert,Users}from"lucide-react";
import{createRoot}from"react-dom/client";import"./styles.css";
type T={id:string,name:string,guests:number,amount:number,plan:"free"|"aycd"|"ala",startedAt?:number};
type A={id:string,type:string,table:string,actor:string,detail:string,amount:number,level:"red"|"orange",at:number,acknowledged:boolean};
const yen=(v:number)=>new Intl.NumberFormat("ja-JP",{style:"currency",currency:"JPY",maximumFractionDigits:0}).format(v);
const init:T[]=[{id:"C1",name:"Counter 1",guests:1,amount:2500,plan:"aycd",startedAt:Date.now()-38*60000},{id:"C2",name:"Counter 2",guests:0,amount:0,plan:"free"},{id:"T1",name:"Table A",guests:4,amount:7800,plan:"ala"},{id:"T2",name:"Table B",guests:2,amount:3000,plan:"aycd",startedAt:Date.now()-52*60000},{id:"T3",name:"Table C",guests:0,amount:0,plan:"free"}];
const menu=[["チャージ",500,"基本"],["飲み放題 1h",1000,"基本"],["ワンドリンク",500,"ドリンク"],["瓶ビール",700,"ドリンク"],["テキーラ",500,"ショット"],["ウォッカ",500,"ショット"],["シロック",800,"ショット"],["1800",1000,"ショット"],["ピッチャー",2500,"ドリンク"],["吉四六",8000,"ボトル"],["カフェパリ",8000,"ボトル"],["オリシャン",13000,"ボトル"],["モエ",20000,"ボトル"],["ヴーヴ",22000,"ボトル"],["モエロゼ",23000,"ボトル"],["PJ",28000,"ボトル"],["ドンペリ",88000,"ボトル"]] as const;
function App(){const[login,setLogin]=useState(false),[pin,setPin]=useState(""),[page,setPage]=useState("home"),[tables,setTables]=useState<T[]>(()=>JSON.parse(localStorage.getItem("baros_tables")||"null")||init),[sel,setSel]=useState("C1"),[audits,setAudits]=useState<A[]>(()=>JSON.parse(localStorage.getItem("baros_audits")||"[]")),[clock,setClock]=useState(()=>localStorage.getItem("baros_clock")==="1");
useEffect(()=>localStorage.setItem("baros_tables",JSON.stringify(tables)),[tables]);useEffect(()=>localStorage.setItem("baros_audits",JSON.stringify(audits)),[audits]);useEffect(()=>localStorage.setItem("baros_clock",clock?"1":"0"),[clock]);
const sales=useMemo(()=>tables.reduce((s,t)=>s+t.amount,0),[tables]),guests=useMemo(()=>tables.reduce((s,t)=>s+t.guests,0),[tables]),unc=audits.filter(a=>!a.acknowledged).length,cur=tables.find(t=>t.id===sel)!;
const add=(name:string,price:number)=>setTables(x=>x.map(t=>t.id===sel?{...t,amount:t.amount+price}:t));
const service=(name:string,price:number)=>setAudits(x=>[{id:crypto.randomUUID(),type:"サービス",table:cur.name,actor:"武田",detail:name+" をサービス",amount:price,level:price>=5000?"red":"orange",at:Date.now(),acknowledged:false},...x]);
const enter=(id:string)=>setTables(x=>x.map(t=>t.id===id?{...t,guests:2,amount:2000,plan:"aycd",startedAt:Date.now()}:t));
const checkout=()=>{setTables(x=>x.map(t=>t.id===sel?{...t,guests:0,amount:0,plan:"free",startedAt:undefined}:t));setPage("tables")};
if(!login)return <div className="login"><div className="brand">BAR <span>OS</span></div><div className="subtitle">CHANCE · STAFF LOGIN</div><div className="pinDots">{[0,1,2,3].map(i=><i key={i} className={i<pin.length?"on":""}/>)}</div><div className="keypad">{[1,2,3,4,5,6,7,8,9].map(n=><button onClick={()=>pin.length<4&&setPin(pin+n)}>{n}</button>)}<button onClick={()=>setPin("")}>C</button><button onClick={()=>pin.length<4&&setPin(pin+"0")}>0</button><button className="gold" onClick={()=>pin.length===4&&setLogin(true)}>入店</button></div><p className="hint">デモ：4桁ならログインできます</p></div>;
return <div className="app"><aside><div className="sideBrand">BAR <span>OS</span><small>CHANCE</small></div><Nav i={<LayoutDashboard/>} l="ホーム" a={page==="home"} f={()=>setPage("home")}/><Nav i={<Users/>} l="席・注文" a={page==="tables"||page==="order"} f={()=>setPage("tables")}/><Nav i={<ShieldAlert/>} l={"重要操作 "+(unc?"("+unc+")":"")} a={page==="audit"} f={()=>setPage("audit")}/><Nav i={<Package/>} l="在庫" a={page==="inventory"} f={()=>setPage("inventory")}/><Nav i={<Clock3/>} l="勤怠" a={page==="attendance"} f={()=>setPage("attendance")}/><div className="spacer"/><Nav i={<LogOut/>} l="ログアウト" f={()=>setLogin(false)}/></aside><main><header><div><b>BAR OS</b><span>運営ダッシュボード</span></div><button className="bell" onClick={()=>setPage("audit")}><Bell/>{unc>0&&<em>{unc}</em>}</button></header>
{page==="home"&&<>{unc>0&&<div className="alertBanner" onClick={()=>setPage("audit")}><ShieldAlert/><b>未確認の重要操作が {unc} 件あります</b><span>確認する →</span></div>}<section className="hero"><p>本日の営業</p><h1>{yen(sales)}</h1><span>{guests}名 来店中</span></section><div className="stats"><Card t="現在客数" v={guests+"名"} s="店内"/><Card t="平均客単価" v={guests?yen(Math.round(sales/guests)):"¥0"} s="リアルタイム"/><Card t="サービス" v={yen(audits.reduce((s,a)=>s+a.amount,0))} s="本日記録"/><Card t="重要操作" v={unc+"件"} s="未確認"/></div><div className="quick"><button onClick={()=>setPage("tables")}><Plus/>新規来店</button><button onClick={()=>setPage("tables")}><GlassWater/>注文</button><button onClick={()=>setPage("tables")}><CreditCard/>会計</button><button onClick={()=>setPage("attendance")}><Clock3/>勤怠</button></div></>}
{page==="tables"&&<><Title h="席管理" p="空席タップで新規来店・利用中席で注文"/><div className="tableGrid">{tables.map(t=>{const r=t.plan==="aycd"&&t.startedAt?60-Math.floor((Date.now()-t.startedAt)/60000):null;return <button className={"tableCard "+(t.guests?"busy":"empty")+" "+(r!==null&&r<=10?"danger":"")} onClick={()=>{setSel(t.id);t.guests?setPage("order"):enter(t.id)}}><strong>{t.name}</strong><span>{t.guests?t.guests+"名":"空席"}</span>{t.guests>0&&<><b>{yen(t.amount)}</b>{r!==null&&<small>飲放 残り {Math.max(r,0)}分</small>}</>}</button>})}</div></>}
{page==="order"&&<><div className="pageTitle"><div><h2>{cur.name}</h2><p>{cur.guests}名 · 現在 {yen(cur.amount)}</p></div><button className="checkout" onClick={checkout}><ReceiptText/> 会計</button></div><div className="menuGrid">{menu.map(m=><div className="menuItem"><small>{m[2]}</small><b>{m[0]}</b><span>{yen(m[1])}</span><div><button onClick={()=>add(m[0],m[1])}>追加</button><button className="service" onClick={()=>service(m[0],m[1])}>サービス</button></div></div>)}</div></>}
{page==="audit"&&<><Title h="重要操作ログ" p="サービス・値引き・取消・返金など"/><div className="auditList">{audits.length===0?<div className="emptyState">重要操作はまだありません</div>:audits.map(a=><div className={"audit "+a.level}><div><b>{a.type} · {a.table}</b><span>{a.detail}</span><small>{a.actor} · {new Date(a.at).toLocaleString("ja-JP")}</small></div><div className="auditRight"><strong>{yen(a.amount)}</strong>{a.acknowledged?<span className="ok">確認済</span>:<button onClick={()=>setAudits(x=>x.map(y=>y.id===a.id?{...y,acknowledged:true}:y))}>確認しました</button>}</div></div>)}</div></>}
{page==="inventory"&&<><Title h="在庫" p="MVP簡易表示"/><div className="inventory">{["角瓶","ニッカ","テキーラ","ウォッカ","吉四六","モエ","ヴーヴ"].map((x,i)=>{const v=[42,61,18,34,26,8,5][i];return <div><b>{x}</b><span>{v}%</span><progress max="100" value={v}/></div>})}</div></>}
{page==="attendance"&&<><Title h="勤怠" p="武田 裕"/><div className="attendanceCard"><Clock3/><h3>{clock?"出勤中":"未出勤"}</h3><p>{clock?"本日の勤務を記録しています":"出勤ボタンを押してください"}</p><button onClick={()=>setClock(!clock)}>{clock?"退勤する":"出勤する"}</button></div></>}</main></div>}
function Nav(p:{i:React.ReactNode,l:string,a?:boolean,f:()=>void}){return <button className={"nav "+(p.a?"active":"")} onClick={p.f}>{p.i}<span>{p.l}</span></button>}function Card(p:{t:string,v:string,s:string}){return <div className="card"><span>{p.t}</span><b>{p.v}</b><small>{p.s}</small></div>}function Title(p:{h:string,p:string}){return <div className="pageTitle"><div><h2>{p.h}</h2><p>{p.p}</p></div></div>}
createRoot(document.getElementById("root")!).render(<App/>);